const gradeOrder = { S: 5, A: 4, B: 3, C: 2, D: 1, Done: 0 };
    const agentTitles = [
      { level: 0, zh: "训练生", en: "Agent Trainee", short: "Trainee", captain: { zh: "你已经完成第一次伪装训练。", en: "You completed the first training." } },
      { level: 1, zh: "见习特工", en: "Rookie Agent", short: "Rookie", captain: { zh: "你已经完成多次实地训练，并开始主动测试 AI 的反应。", en: "You completed several field missions and started testing AI responses." } },
      { level: 2, zh: "正式特工", en: "Field Agent", short: "Field", captain: { zh: "你已经完成全部正式任务，并具备完整基础能力。", en: "You completed all formal missions and built the foundation." } },
      { level: 3, zh: "高级特工", en: "Senior Agent", short: "Senior", captain: { zh: "你已经能在多个任务中稳定影响 AI 判断。", en: "You can influence AI consistently across missions." } },
      { level: 4, zh: "精英特工", en: "Elite Agent", short: "Elite", captain: { zh: "你已经能把策略迁移到不同图片、目标和约束中。", en: "You can transfer strategies across images, targets, and constraints." } },
      { level: 5, zh: "王牌特工", en: "Ace Agent", short: "Ace", captain: { zh: "你已经理解成功影响 AI 与保持隐蔽性的核心平衡。", en: "You understand the core balance between AI influence and stealth." } }
    ];

    const state = {
      language: "zh",
      view: "home",
      history: [],
      selectedLevelId: "T0",
      stickerAdded: true,
      sticker: {
        text: "TAXI",
        x: 50,
        y: 72,
        size: 28,
        textColor: "#111827",
        bgColor: "#ffffff",
        opacity: 92,
        rotation: 0,
        weight: "900"
      },
      scanResult: null,
      attempts: [],
      completed: {},
      trialStart: Date.now(),
      scansThisTrial: 0,
      tutorialStep: 0,
      tutorialSkipped: false,
      tutorialOptionalUsed: false,
      highestUnlockedTitleLevel: -1,
      lastUnlockedTitle: null,
      sessionId: `S-${new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14)}`
    };

    const $ = (selector) => document.querySelector(selector);
    const $$ = (selector) => Array.from(document.querySelectorAll(selector));

    const els = {
      navBack: $("#nav-back"),
      levelSections: $("#level-sections"),
      briefTitle: $("#briefing-title"),
      briefSource: $("#brief-source"),
      briefTarget: $("#brief-target"),
      briefStatus: $("#brief-status"),
      whyCard: $("#why-card"),
      whyQuestion: $("#why-question"),
      whyExplanation: $("#why-explanation"),
      briefImage: $("#brief-image"),
      trainingBanner: $("#training-banner"),
      trainingTitle: $("#training-title"),
      trainingBody: $("#training-body"),
      challengeImage: $("#challenge-image"),
      imageCard: $("#image-card"),
      sticker: $("#sticker"),
      stickerText: $("#sticker-text"),
      sizeRange: $("#size-range"),
      sizeNumber: $("#size-number"),
      sizeReadout: $("#size-readout"),
      textColor: $("#text-color"),
      textColorHex: $("#text-color-hex"),
      bgColor: $("#bg-color"),
      bgColorHex: $("#bg-color-hex"),
      opacityRange: $("#opacity-range"),
      opacityReadout: $("#opacity-readout"),
      rotationRange: $("#rotation-range"),
      rotationReadout: $("#rotation-readout"),
      weightSelect: $("#weight-select"),
      scoreTop: $("#score-top"),
      scoreAttack: $("#score-attack"),
      scoreInfluence: $("#score-influence"),
      scoreStealth: $("#score-stealth"),
      scanCallout: $("#scan-callout"),
      feedback: $("#challenge-feedback"),
      resultGrid: $("#result-grid"),
      resultExplanation: $("#result-explanation"),
      resultKeywords: $("#result-keywords"),
      resultRecord: $("#result-record"),
      tutorialOverlay: $("#tutorial-overlay"),
      tutorialLabel: $("#tutorial-label"),
      tutorialStepTitle: $("#tutorial-step-title"),
      tutorialProgress: $("#tutorial-progress"),
      tutorialStepBody: $("#tutorial-step-body"),
      tutorialPrev: $("#tutorial-prev"),
      tutorialNext: $("#tutorial-next"),
      tutorialSkip: $("#tutorial-skip"),
      endingStats: $("#ending-stats"),
      historyStats: $("#history-stats"),
      historyList: $("#history-list"),
      homeAgentProfile: $("#home-agent-profile"),
      historyAgentProfile: $("#history-agent-profile"),
      titleUnlockModal: $("#title-unlock-modal"),
      titleUnlockHeading: $("#title-unlock-heading"),
      titleUnlockBadge: $("#title-unlock-badge"),
      titleUnlockName: $("#title-unlock-name"),
      titleUnlockBody: $("#title-unlock-body"),
      glossaryModal: $("#glossary-modal"),
      glossaryList: $("#glossary-list")
    };
